site_name: HDCC Sandbox Tutorial
# site_url: https://docs.sandbox-tutorial

theme:
  name: material
  icon:
    logo: material/home
  # logo: assets/images/Lasso-Logo-Reverse-H.svg
  favicon: assets/images/favicon-32x32.png
  features:
    - toc.integrate        # merges page TOC into left navigation instead of right sidebar
    - toc.follow           # highlights active section in TOC as you scroll
    - header.autohide      # hides top header on scroll down, reappears when scrolling up
    - content.image.zoom   # click image to open overlay and zoom
    - content.tooltips     # enable tooltips
    - navigation.instant   # faster page loading (SPA-style navigation)
    - navigation.tracking  # updates URL hash as you scroll through sections
    - navigation.path      # shows breadcrumb-style navigation path at top of page (critical for viewing on small screens/mobile)
  
markdown_extensions:
  - toc:
      toc_depth: 2      # include h2–h3 in TOC (default is deeper - may want to change this)
      permalink: true   # adds link icons to copy section URLs
  - md_in_html
  - pymdownx.superfences

  # Enable callout blocks (admonitions) + collapsible
  - admonition
  - pymdownx.details 

  # CriticMarkup for inline edit annotations (useful for internal notes during dev)
  - pymdownx.critic  

  # Enable tooltips:
  - abbr
  - attr_list

extra:
  generator: false # Remove "Generated by MkDocs" footer
  
plugins:
  - search
  - git-revision-date-localized:
      type: date  

extra_javascript:
  - assets/javascripts/extra.js

extra_css:
  - assets/extra.css
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css

docs_dir: docs

nav:
  # - "<span class='material-icons'>home</span> Home": index.md
  - index.md
  - Access Sandbox: access.md
  - Load Desktop: load_desktop.md
  - R Studio: r_studio.md
  - Volumetric Analysis using Jupyter: volumetric_analysis.md
  - Diffusion Univariate Statistical Testing: model_array.md
  - XCP-D Output Multivariate Prediction: xcpd-multivar-predictions.md
  - Upcoming HDCC Workshop: workshop.md
